
pages:
  stage: deploy
  image: alpine:latest
  script:
    - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
  only:
    - front-archive

test:
  stage: test
  image: python:3.9-slim-buster
  script:
    - echo 'Running tests...'
    - python -m pip install -r requirements.txt
    - python tests/run.py
  only:
    - maine