image: alpine:latest

pages:
  stage: deploy
  script:
    - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
  only:
    - front-archive

test:
  stage: test
  script:
    - echo 'Running tests...'
    - python -m pip install -r requirements.txt
    - python -m ./tests/run.py
  only:
    - maine